artifact_uri: file:///D:/Maestria data science/Nueva carpeta/4to ciclo/MLOPS/mlops_project/trabajo_mlflow/839316353519930301/01a6537d36a84f9aba109f33f0cb0332/artifacts
end_time: 1761840621876
entry_point_name: ''
experiment_id: '839316353519930301'
lifecycle_stage: active
run_id: 01a6537d36a84f9aba109f33f0cb0332
run_name: xgboost_local_run
source_name: ''
source_type: 4
source_version: ''
start_time: 1761840614451
status: 3
tags: []
user_id: rodri
