artifact_location: file:///D:/Maestria data science/Nueva carpeta/4to ciclo/MLOPS/mlops_project/trabajo_mlflow/839316353519930301
creation_time: 1761526445271
experiment_id: '839316353519930301'
last_update_time: 1761526445271
lifecycle_stage: active
name: xgboost_local_experiment
