artifact_uri: file:///D:/Maestria data science/Nueva carpeta/4to ciclo/MLOPS/mlops_project/trabajo_mlflow/839316353519930301/97d0f97343cf4e8a8ed65d39f5f5fd37/artifacts
end_time: 1761526568785
entry_point_name: ''
experiment_id: '839316353519930301'
lifecycle_stage: active
run_id: 97d0f97343cf4e8a8ed65d39f5f5fd37
run_name: xgboost_local_run
source_name: ''
source_type: 4
source_version: ''
start_time: 1761526560249
status: 3
tags: []
user_id: rodri
